### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by liveashish** [caiogondim/bullet-train-oh-my-zsh-theme#96] opened 2015-11-18 20:02 UTC
I am getting:
themes/bullet-train.zsh-theme:5: parse error near `\n'

**Comment by caiogondim** [comment] 2015-11-22 23:22
You running the latest version?
Could you `git pull` just in case?

**Comment by Nuclearfossil** [comment] 2015-12-01 02:02
First time using this theme and getting a similar error:
~/_nixhome/omzsh_customizations/themes/bullet-train-oh-my-zsh-theme/bullet-train.zsh-theme:299: parse error near `]]'

**Comment by caiogondim** [comment] 2015-12-01 23:41
Which OS are you using?

**Comment by Nuclearfossil** [comment] 2015-12-02 00:29
Ubuntu 14 LTS in a Vagrant VM under OSX

**Comment by bdesmarez** [comment] 2015-12-02 13:23
Same problem here, osX ssh to ubuntu

**Comment by caiogondim** [comment] 2015-12-02 13:56
Ok. Seems to be a problem on Linux.
Will debug it.

**Comment by justmark** [comment] 2015-12-02 14:55
Just installed bullet-train on a clean install of Ubuntu 14.04 LTS  with oh-my-zsh.  I'm getting the same parse error near ']]' on line 299, mentioned above.  Am aware you're already looking into this.  Thanks.

**Comment by Talanor** [comment] 2015-12-03 00:47
Hey. Note, I also have this problem:

```
bullet-train.zsh-theme:299: parse error near `]]'
```

On a fresh zsh 5.0.2 install but don't have it on fresh zsh 5.0.7 and 5.2 installs.
Maybe the problem does not come from the script but from a bug introduced in zsh and fixed in the newest versions?

**Comment by KVoll** [comment] 2015-12-03 22:56
I believe commit 3f5691e fixes this issue. Can anyone please try again to confirm?

**Comment by justmark** [comment] 2015-12-04 13:01
@KVoll That worked like a charm!

**Comment by Nuclearfossil** [comment] 2015-12-04 18:52
I just confirmed that 3f5691e fixes the problem for me.

**Comment by caiogondim** [comment] 2015-12-07 10:42
Closing the issue.
Thanks again @KVoll for the amazing work.

**Closed by caiogondim** 2015-12-07 10:42 UTC
